#ifndef ILRD_DHCP_TESTS_FUNCS_H
#define ILRD_DHCP_TESTS_FUNCS_H


int TEST_DHCP_CREATE();
int TEST_DHCP_FREE();
int TEST_DHCP_ALLOC_SUCCESS1();
int TEST_DHCP_ALLOC_SUCCESS2();
int TEST_DHCP_ALLOC_SUCCESS3();
int TEST_DHCP_ALLOC_RESERVED_ADDRESS_FAIL1();
int TEST_DHCP_ALLOC_RESERVED_ADDRESS_FAIL2();
int TEST_DHCP_ALLOC_RESERVED_ADDRESS_FAIL3();
int TEST_DHCP_FREE();







#endif
